apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.cast_db.app }}
  name: cast-db-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: {{ .Values.cast_db.containerPort }}
  selector:
    app: {{ .Values.cast_db.app }}
