apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.cast_svc.app }}
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: {{ .Values.cast_svc.containerPort }}
  selector:
    app: {{ .Values.cast_svc.app }}
status:
  loadBalancer: {}
