{{- if .Values.ClusterIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ClusterIssuer.name }}
spec:
  acme:
# Remember to update this if you use this manifest to obtain real certificates :
    email: ykadi.ykadi@gmail.com
# server:https://acme-staging-v02.api.letsencrypt.org/directory
# To use the production environment, use the following line instead:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name:  {{ .Values.ClusterIssuer.privateKeySecretRef.name }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}