apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data-cast
  name: {{ .Values.volumes.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
status: {}
