apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data-movie
  name: postgres-data-movie
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
