namespace: dev

replicaCount: 1

### Casts app Values ###

cast_db:
   app: cast-db
   containerPort: 5432    
   replicaCount: 1
   configMap: cast-db-conf
   secret: cast-db-password

   

cast_svc:
  app: cast-service
  replicaCount: 1
  containerPort: 8000  
  image:
    name: ykadi/cast-service
    pullPolicy: IfNotPresent
    tag: "v1"
  configMap: cast-svc-conf


#### Ingress Values ###

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: jenkins.devops-youss.cloudns.ph
      # paths:
      #   - path: /api/v1/casts
      #     pathType: Prefix
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local