apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cast_db.configMap }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: cast_db_dev
  POSTGRES_USER: cast_db_username


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cast_svc.configMap }}
  namespace: {{ .Values.namespace }}
data:
  DATABASE_URI: postgresql://cast_db_username:cast_db_password@cast-db-svc/cast_db_dev