apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.movie_svc.app }}
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movie_svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.movie_svc.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.movie_svc.app }}
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CAST_SERVICE_HOST_URL
              value: http://cast_service:8000/api/v1/casts/
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
          image: "{{ .Values.movie_svc.image.name }}:{{ .Values.movie_svc.image.tag }}"
          name: movie-service
          ports:
            - containerPort: {{ .Values.movie_svc.containerPort }}
              protocol: TCP
          resources: {}
          # volumeMounts:
          #   - mountPath: /app
          #     name: movie-service-claim0
      restartPolicy: Always
      # volumes:
      #   - name: movie-service-claim0
      #     persistentVolumeClaim:
      #       claimName: movie-service-claim0
status: {}
