apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-service
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: movie-service
status:
  loadBalancer: {}
