apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movie-service
  name: movie-service
  namespace: default
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8000
  selector:
    app: movie-service
status:
  loadBalancer: {}
